region: "{{ must_env `AWS_REGION` }}"
cluster: ec-api-prod
service: ec-api-prod-order-consumer
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m
plugins:
  - name: tfstate
    config:
      url: s3://REPLACE_ME_ec-api-tfstate/ec-api/terraform.tfstate
